title: "Conta Propria"
description: "Para entender tudo sobre dados, desde o mais básico até inteligência artificial, e como colocar tudo isso em prática|
🎥 quartas-feiras aaa10 18h"
Logo: (/assets/logo.png)
theme: minimal
