title: "Conta Propria"
description: "Para entender tudo sobre dados, desde o mais básico até inteligência artificial, e como colocar tudo isso em prática|
🎥 quartas-feiras aaa11 18h"
logo: /assets/logo.png

theme: jekyll-theme-minimal
