theme: jekyll-theme-minimal
title: [Conta Própria]
description: [Para entender tudo sobre dados, desde o mais básico até inteligência artificial, e como colocar tudo isso em prática
🎥 quartas-feiras 18h]
logo: [ce8b2f2a-4e83-4ddf-9fab-443fb47962b2.jpg]
